package bpy.types;
@:pythonImport("bpy.types") extern class DomainFluidSettings extends FluidSettings {
	/**
		Allowed compressibility due to gravitational force for standing fluid (directly affects simulation step size)
	**/
	public var compressibility : Float;
	/**
		Simulation time of the last blender frame (in seconds)
	**/
	public var end_time : Float;
	/**
		Directory (and/or filename prefix) to store baked fluid simulation files in
	**/
	public var filepath : String;
	/**
		Vertices of the fluid mesh generated by simulation
	**/
	public var fluid_mesh_vertices : Collection<FluidVertexVelocity>;
	/**
		Offset when reading baked cache
	**/
	public var frame_offset : Int;
	/**
		Amount of particles to generate (0=off, 1=normal, >1=more)
	**/
	public var generate_particles : Float;
	/**
		Gravity in X, Y and Z direction
	**/
	public var gravity : mathutils.Vector;
	/**
		Number of coarsened grids to use (-1 for automatic)
	**/
	public var grid_levels : Int;
	/**
		Estimated amount of memory needed for baking the domain
	**/
	public var memory_estimate : String;
	/**
		Amount of mixing between no- and free-slip, 0 is no slip and 1 is free slip
	**/
	public var partial_slip_factor : Float;
	/**
		Preview resolution in X,Y and Z direction
	**/
	public var preview_resolution : Int;
	/**
		How to display the mesh for rendering
	**/
	public var render_display_mode : String;
	/**
		Domain resolution in X,Y and Z direction
	**/
	public var resolution : Int;
	/**
		Fluid motion rate (0 = stationary, 1 = normal speed)
	**/
	public var simulation_rate : Float;
	/**
		Size of the simulation domain in meters
	**/
	public var simulation_scale : Float;
	public var slip_type : String;
	/**
		Simulation time of the first blender frame (in seconds)
	**/
	public var start_time : Float;
	/**
		Amount of surface smoothing (a value of 0 is off, 1 is normal smoothing and more than 1 is extra smoothing)
	**/
	public var surface_smooth : Float;
	/**
		Number of isosurface subdivisions (this is necessary for the inclusion of particles into the surface generation - WARNING: can lead to longer computation times !)
	**/
	public var surface_subdivisions : Int;
	/**
		Override number of threads for the simulation, 0 is automatic
	**/
	public var threads : Int;
	/**
		Number of tracer particles to generate
	**/
	public var tracer_particles : Int;
	/**
		Reverse fluid frames
	**/
	public var use_reverse_frames : Bool;
	/**
		Generate speed vectors for vector blur
	**/
	public var use_speed_vectors : Bool;
	/**
		Removes the air gap between fluid surface and obstacles - WARNING: Can result in a dissolving surface in other areas
	**/
	public var use_surface_noobs : Bool;
	/**
		Use a custom start and end time (in seconds) instead of the scene's timeline
	**/
	public var use_time_override : Bool;
	/**
		How to display the mesh in the viewport
	**/
	public var viewport_display_mode : String;
	/**
		Viscosity setting: value that is multiplied by 10 to the power of (exponent*-1)
	**/
	public var viscosity_base : Float;
	/**
		Negative exponent for the viscosity value (to simplify entering small values e.g. 5*10^-6)
	**/
	public var viscosity_exponent : Int;
}