package bpy.types;
@:pythonImport("bpy.types") extern class FModifierGenerator extends FModifier {
	/**
		Coefficients for 'x' (starting from lowest power of x^0)
	**/
	public var coefficients : Array<Float>;
	/**
		Type of generator to use
	**/
	public var mode : String;
	/**
		The highest power of 'x' for this polynomial (number of coefficients - 1)
	**/
	public var poly_order : Int;
	/**
		Values generated by this modifier are applied on top of the existing values instead of overwriting them
	**/
	public var use_additive : Bool;
}