package bpy.types;
@:pythonImport("bpy.types") extern class FModifierFunctionGenerator extends FModifier {
	/**
		Scale factor determining the maximum/minimum values
	**/
	public var amplitude : Float;
	/**
		Type of built-in function to use
	**/
	public var function_type : String;
	/**
		Scale factor determining the 'speed' of the function
	**/
	public var phase_multiplier : Float;
	/**
		Constant factor to offset time by for function
	**/
	public var phase_offset : Float;
	/**
		Values generated by this modifier are applied on top of the existing values instead of overwriting them
	**/
	public var use_additive : Bool;
	/**
		Constant factor to offset values by
	**/
	public var value_offset : Float;
}