package bpy.ops;
@:pythonImport("bpy.ops.gpencil") extern class Gpencil {
	/**
		 Delete the active frame for the active Grease Pencil Layer
	**/
	public static function active_frame_delete():Void;
	/**
		 Delete the active frame(s) of all editable Grease Pencil layers
	**/
	public static function active_frames_delete_all():Void;
	/**
		 Insert a blank frame on the current frame (all subsequently existing frames, if any, are shifted right by one frame)
	**/
	public static function blank_frame_add(?all_layers:Bool = false):Void;
	/**
		 Add new Grease Pencil drawing brush for the active Grease Pencil data-block
	**/
	public static function brush_add():Void;
	/**
		 Change active Grease Pencil drawing brush
	**/
	public static function brush_change(?brush:String = "DEFAULT"):Void;
	/**
		 Copy current Grease Pencil drawing brush
	**/
	public static function brush_copy():Void;
	/**
		 Move the active Grease Pencil drawing brush up/down in the list
	**/
	public static function brush_move(?type:String = "UP"):Void;
	/**
		 Apply tweaks to strokes by painting over the strokes
	**/
	public static function brush_paint(?stroke:Collection<OperatorStrokeElement> = null, ?wait_for_input:Bool = true):Void;
	/**
		 Create a set of predefined Grease Pencil drawing brushes
	**/
	public static function brush_presets_create():Void;
	/**
		 Remove active Grease Pencil drawing brush
	**/
	public static function brush_remove():Void;
	/**
		 Select a Grease Pencil drawing brush
	**/
	public static function brush_select(?index:Int = 0):Void;
	/**
		 Convert the active Grease Pencil layer to a new Curve Object
	**/
	public static function convert(?type:String = "PATH", ?use_normalize_weights:Bool = true, ?radius_multiplier:Float = 1.0, ?use_link_strokes:Bool = true, ?timing_mode:String = "FULL", ?frame_range:Int = 100, ?start_frame:Int = 1, ?use_realtime:Bool = false, ?end_frame:Int = 250, ?gap_duration:Float = 0.0, ?gap_randomness:Float = 0.0, ?seed:Int = 0, ?use_timing_data:Bool = false):Void;
	/**
		 Copy selected Grease Pencil points and strokes
	**/
	public static function copy():Void;
	/**
		 Add new Grease Pencil data-block
	**/
	public static function data_add():Void;
	/**
		 Unlink active Grease Pencil data-block
	**/
	public static function data_unlink():Void;
	/**
		 Delete selected Grease Pencil strokes, vertices, or frames
	**/
	public static function delete(?type:String = "POINTS"):Void;
	/**
		 Delete selected points without splitting strokes
	**/
	public static function dissolve():Void;
	/**
		 Make annotations on the active data
	**/
	public static function draw(?mode:String = "DRAW", ?stroke:Collection<OperatorStrokeElement> = null, ?wait_for_input:Bool = true):Void;
	/**
		 Duplicate the selected Grease Pencil strokes
	**/
	public static function duplicate():Void;
	/**
		 Make copies of the selected Grease Pencil strokes and move them
	**/
	public static function duplicate_move(?GPENCIL_OT_duplicate:Dynamic = null, ?TRANSFORM_OT_translate:Dynamic = null):Void;
	/**
		 Enter/Exit edit mode for Grease Pencil strokes
	**/
	public static function editmode_toggle():Void;
	/**
		 Hide selected/unselected Grease Pencil layers
	**/
	public static function hide(?unselected:Bool = false):Void;
	/**
		 Interpolate grease pencil strokes between frames
	**/
	public static function interpolate(?shift:Float = 0.0):Void;
	/**
		 Remove breakdown frames generated by interpolating between two Grease Pencil frames
	**/
	public static function interpolate_reverse():Void;
	/**
		 Generate 'in-betweens' to smoothly interpolate between Grease Pencil frames
	**/
	public static function interpolate_sequence():Void;
	/**
		 Add new Grease Pencil layer for the active Grease Pencil data-block
	**/
	public static function layer_add():Void;
	/**
		 Change active Grease Pencil layer
	**/
	public static function layer_change(?layer:String = "DEFAULT"):Void;
	/**
		 Make a copy of the active Grease Pencil layer
	**/
	public static function layer_duplicate():Void;
	/**
		 Toggle whether the active layer is the only one that can be edited and/or visible
	**/
	public static function layer_isolate(?affect_visibility:Bool = false):Void;
	/**
		 Merge the current layer with the layer below
	**/
	public static function layer_merge():Void;
	/**
		 Move the active Grease Pencil layer up/down in the list
	**/
	public static function layer_move(?type:String = "UP"):Void;
	/**
		 Remove active Grease Pencil layer
	**/
	public static function layer_remove():Void;
	/**
		 Lock all Grease Pencil layers to prevent them from being accidentally modified
	**/
	public static function lock_all():Void;
	/**
		 Move selected strokes to another layer
	**/
	public static function move_to_layer(?layer:String = "DEFAULT"):Void;
	/**
		 Add new Grease Pencil palette for the active Grease Pencil data-block
	**/
	public static function palette_add():Void;
	/**
		 Change active Grease Pencil palette
	**/
	public static function palette_change(?palette:String = "DEFAULT"):Void;
	/**
		 Lock and hide any color not used in any layer
	**/
	public static function palette_lock_layer():Void;
	/**
		 Remove active Grease Pencil palette
	**/
	public static function palette_remove():Void;
	/**
		 Add new Grease Pencil palette color for the active Grease Pencil data-block
	**/
	public static function palettecolor_add():Void;
	/**
		 Copy current Grease Pencil palette color
	**/
	public static function palettecolor_copy():Void;
	/**
		 Hide selected/unselected Grease Pencil colors
	**/
	public static function palettecolor_hide(?unselected:Bool = false):Void;
	/**
		 Toggle whether the active color is the only one that is editable and/or visible
	**/
	public static function palettecolor_isolate(?affect_visibility:Bool = false):Void;
	/**
		 Lock all Grease Pencil colors to prevent them from being accidentally modified
	**/
	public static function palettecolor_lock_all():Void;
	/**
		 Move the active Grease Pencil palette color up/down in the list
	**/
	public static function palettecolor_move(?direction:String = "UP"):Void;
	/**
		 Remove active Grease Pencil palette color
	**/
	public static function palettecolor_remove():Void;
	/**
		 Unhide all hidden Grease Pencil palette colors
	**/
	public static function palettecolor_reveal():Void;
	/**
		 Select all Grease Pencil strokes using current color
	**/
	public static function palettecolor_select():Void;
	/**
		 Unlock all Grease Pencil colors so that they can be edited
	**/
	public static function palettecolor_unlock_all():Void;
	/**
		 Paste previously copied strokes or copy and merge in active layer
	**/
	public static function paste(?type:String = "COPY"):Void;
	/**
		 Reproject the selected strokes from the current viewpoint as if they had been newly drawn (e.g. to fix problems from accidental 3D cursor movement or accidental viewport changes, or for matching deforming geometry)
	**/
	public static function reproject(?type:String = "PLANAR"):Void;
	/**
		 Show all Grease Pencil layers
	**/
	public static function reveal():Void;
	/**
		 Select Grease Pencil strokes and/or stroke points
	**/
	public static function select(?extend:Bool = false, ?deselect:Bool = false, ?toggle:Bool = false, ?entire_strokes:Bool = false, ?location:Array<Int> = null):Void;
	/**
		 Change selection of all Grease Pencil strokes currently visible
	**/
	public static function select_all(?action:String = "TOGGLE"):Void;
	/**
		 Select Grease Pencil strokes within a rectangular region
	**/
	public static function select_border(?gesture_mode:Int = 0, ?xmin:Int = 0, ?xmax:Int = 0, ?ymin:Int = 0, ?ymax:Int = 0, ?extend:Bool = true):Void;
	/**
		 Select Grease Pencil strokes using brush selection
	**/
	public static function select_circle(?x:Int = 0, ?y:Int = 0, ?radius:Int = 1, ?gesture_mode:Int = 0):Void;
	/**
		 Select first point in Grease Pencil strokes
	**/
	public static function select_first(?only_selected_strokes:Bool = false, ?extend:Bool = false):Void;
	/**
		 Select all strokes with similar characteristics
	**/
	public static function select_grouped(?type:String = "LAYER"):Void;
	/**
		 Select Grease Pencil strokes using lasso selection
	**/
	public static function select_lasso(?path:Collection<OperatorMousePath> = null, ?deselect:Bool = false, ?extend:Bool = true):Void;
	/**
		 Select last point in Grease Pencil strokes
	**/
	public static function select_last(?only_selected_strokes:Bool = false, ?extend:Bool = false):Void;
	/**
		 Shrink sets of selected Grease Pencil points
	**/
	public static function select_less():Void;
	/**
		 Select all points in same strokes as already selected points
	**/
	public static function select_linked():Void;
	/**
		 Grow sets of selected Grease Pencil points
	**/
	public static function select_more():Void;
	/**
		 Hide/Unhide selected points for Grease Pencil strokes setting alpha factor
	**/
	public static function selection_opacity_toggle():Void;
	/**
		 Snap cursor to center of selected points
	**/
	public static function snap_cursor_to_selected():Void;
	/**
		 Snap selected points/strokes to the cursor
	**/
	public static function snap_to_cursor(?use_offset:Bool = true):Void;
	/**
		 Snap selected points to the nearest grid points
	**/
	public static function snap_to_grid():Void;
	/**
		 Apply the thickness change of the layer to its strokes
	**/
	public static function stroke_apply_thickness():Void;
	/**
		 Arrange selected strokes up/down in the drawing order of the active layer
	**/
	public static function stroke_arrange(?direction:String = "UP"):Void;
	/**
		 Move selected strokes to active color
	**/
	public static function stroke_change_color():Void;
	/**
		 Close or open the selected stroke adding an edge from last to first point
	**/
	public static function stroke_cyclical_set(?type:String = "TOGGLE"):Void;
	/**
		 Change direction of the points of the selected strokes
	**/
	public static function stroke_flip():Void;
	/**
		 Join selected strokes (optionally as new stroke)
	**/
	public static function stroke_join(?type:String = "JOIN", ?leave_gaps:Bool = false):Void;
	/**
		 Lock any color not used in any selected stroke
	**/
	public static function stroke_lock_color():Void;
	/**
		 Subdivide between continuous selected points of the stroke adding a point half way between them
	**/
	public static function stroke_subdivide(?number_cuts:Int = 1):Void;
	/**
		 Unlock all Grease Pencil layers so that they can be edited
	**/
	public static function unlock_all():Void;
}